### ISSUE TITLE
Create a data structure to make easy the reporting

### ISSUE THREAD

**Issue by aquintanas** [limdor/p2p-lending#37]
I believe that a data structure is needed to make more straightforward statistics computation and reporting. I want to discuss if it is necessary and how it should be.

I propose to have a class with the aggregated investment data frame. Then, the functions that calculate statistics can work with this class to set the necessary information. 

I think that this will help to split the reporting functions without duplicating some operations. For instance, we can compute country and loan originator percentages by computing once the total investment. 

@limdor, what do you think? Can we arrange a call to talk about this possibility?

**Comment by limdor** [comment]
Sounds good!

**Comment by aquintanas** [comment]
We can take advantage of the [original properties definition](https://pandas.pydata.org/docs/development/extending.html#:~:text=Define%20original%20properties-,%C2%B6,-To%20let%20original) available in `pandas`.

**Comment by aquintanas** [comment]
@limdor, regarding caching some computations that we spoke about early this week. What do you think about my cache decorator? Can it be improved to achieve what we discussed?

````
CACHE = {}

def cache(fun):
    def wrapper(*args, **kwargs):
        if id(args[0]) not in CACHE.keys():
            print(f'Caching {id(args[0])}')
            CACHE[id(args[0])] = fun(*args, **kwargs)
        return CACHE[id(args[0])]
    return wrapper

class MyClass:
    i = [1,2,3,4]
    
@cache
def compute(x):
    return sum(x.i)

if __name__ == '__main__':
    
    a = MyClass()
    print(compute(a))
    print(compute(a))
    b = MyClass()
    print(compute(b))
````

The output is:

````
Caching 4317487008
10
10
10
Caching 4317486960
10
````
