### ISSUE TITLE
Report a rough estimation of how much income will be generated the following month

### ISSUE THREAD

**Issue by limdor** [limdor/p2p-lending#38]
For a given point in time we have the list of all credits with the amount of each of them and the interest.
This information is enough to report a rough estimation on how much income will be generated the next month.

For example:
100€ at 7%
50€ at 2%
would generate each
100 * 0.07 / 12 = 0.58€
50 * 0.02 / 12 = 0.08€
and in this case we would report that for next month there will be an income of 0.66€.

Of course this is not correct because a lot of parameters should be consider but this would give a rough estimation.
Some of the cases where this would fail:
* if the payment is delayed
* if the investment finishes before of the end of the month

**Comment by aquintanas** [comment]
This feature is part of the overall report. Isn't it?

**Comment by limdor** [comment]
Most probably, if we want to have a section of forecast in the future, this might go to forecast.

**Comment by aquintanas** [comment]
I like the idea of a forecast report.

**Comment by aquintanas** [comment]
@limdor, If we separate the functions from the data class, should we use [dataclasses](https://docs.python.org/es/3.8/library/dataclasses.html)?

**Comment by limdor** [comment]
I've heard very good things about dataclasses but I barely haven't used them. We just need to check which specific operators we want generated and limit it to these ones (afaik is possible).  You can end up with generated methods that are not what you would expect for the specific class or some that you don't need.

**Comment by aquintanas** [comment]
Let's talk about this in a call.

**Comment by limdor** [comment]
Closing manually the issue. It was merged in 157d973ddde629f96b1784303ffe5577e4bf0659 but somehow github did not detect it.
