### ISSUE TITLE
Change text appearing on mouse over

### ISSUE THREAD

**Issue by limdor** [limdor/p2p-lending#64]
Change the text that appears on the pie chart on mouse over to show only the outstanding principal.
Instead of the following image:
![image](https://user-images.githubusercontent.com/3073717/149676028-7cee863e-cba1-4b61-9d5c-aa4ac17ac42e.png)
It should show only the value underlined in read formatted with 2 decimals with the euro sign. (13.499,23€)

**Comment by aquintanas** [comment]
solved in #66
